
required = "%s обязательное поле."
lte = "%s должно быть меньше %v"
gte = "%s должно быть больше %v"
email = "%s не является действительным email адресом."
url = "%s не является действительным url."
oneof = "%s должен быть одним из %v"

first_name = "имя"
second_name = "фамилия"
email = "email"
phone_number = "телефон"
status = "статус"
password = "пароль"
url = "url"
alias = "алиас"
id = "id"
created_at = "дата создания"
updated_at = "дата обновления"
username = "юзернейм"
age = "возраст"
gender = "пол"