required = "%s is a required field."
lte = "%s should be lower than %v"
gte = "%s should be greater than %v"
email = "%s is not a valid email address."
url = "%s is not a valid url."
oneof = "%s should be one of the %v"

first_name = "first name"
second_name = "second name"
email = "email"
phone_number = "phone number"
status = "status"
password = "password"
url = "url"
alias = "alias"
id = "id"
created_at = "created at"
updated_at = "updated at"
username = "username"
age = "age"
gender = "gender"